name: Packer Build with Logging
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
env:
  GOFLAGS: "-trimpath"
  GOX_OUTPUT: "release/{{.Arch}}/{{.OS}}/{{.Dir}}"
  GOX_TEST_OUTPUT: "test/{{.Arch}}/{{.OS}}/bin/{{.Dir}}"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  gh_ci_key: ${{ secrets.GH_CI_KEY }}
  S3_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  S3_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  LOGSTASH_ENDPOINT: ${{ secrets.LOGSTASH_ENDPOINT }}
jobs:
  build:
    name: Packer Build using GH Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create files
        run: |
          echo "${{ secrets.BEATS_CRT }}" > beats.crt
          echo "${{ secrets.BEATS_KEY }}" > beats.key
          echo "${{ secrets.LOGSTASH_CRT }}" > logstashCA.crt
      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
          unzip packer_1.6.0_linux_amd64.zip
          sudo mv packer /usr/local/bin/
        shell: bash
      - name: Configure AWS credentials
        run: |
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
      - name: Build AMI with Packer
        run: |
          packer init /home/runner/work/ziti-tests-ami/ziti-tests-ami
          packer build /home/runner/work/ziti-tests-ami/ziti-tests-ami/ziti-ami.pkr.hcl