name: Packer Build with Logging
on:
  workflow_dispatch:
  push:
    branches:
      #      - main
      - *
env:
  GOFLAGS: "-trimpath"
  GOX_OUTPUT: "release/{{.Arch}}/{{.OS}}/{{.Dir}}"
  GOX_TEST_OUTPUT: "test/{{.Arch}}/{{.OS}}/bin/{{.Dir}}"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  gh_ci_key: ${{ secrets.GH_CI_KEY }}
  S3_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  S3_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  LOGSTASH_ENDPOINT: ${{ secrets.LOGSTASH_ENDPOINT }}
jobs:
  build:
    name: Packer Build using GH Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create files
        run: |
          mkdir etc/log/
          echo "${{ secrets.BEATS_CRT }}" > etc/log/beats.crt
          echo "${{ secrets.BEATS_KEY }}" > etc/log/beats.key
          echo "${{ secrets.LOGSTASH_CRT }}" > etc/log/logstash.crt
      - name: Packer Validate and Build
        run: |
          cd ami/
          packer validate ziti-ami.pkr.hcl
          packer build ziti-ami.pkr.hcl
